# Generated by Django 5.2.3 on 2025-06-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_vendorproduct_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='VendorProduct',
        ),
    ]
