# Generated by Django 5.2.4 on 2025-07-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='users.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='users.user'),
        ),
    ]
