# Generated by Django 5.2.3 on 2025-06-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
