# Generated by Django 5.2.3 on 2025-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
