# Generated by Django 5.2.3 on 2025-07-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_id_cartitem_cart_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='cart_id',
        ),
    ]
