# Generated by Django 5.2.4 on 2025-07-05 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleditem',
            options={'verbose_name': 'Scheduled Item', 'verbose_name_plural': 'Scheduled Items'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionbox',
            options={'verbose_name': 'Subscription Box', 'verbose_name_plural': 'Subscription Boxes'},
        ),
        migrations.RemoveField(
            model_name='subscriptionbox',
            name='user',
        ),
        migrations.AddField(
            model_name='subscriptionbox',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text="User of type 'customer'", limit_choices_to={'type': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscriptions', to='users.user'),
        ),
        migrations.AddField(
            model_name='subscriptionbox',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text="User of type 'vendor'", limit_choices_to={'type': 'vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subscriptions', to='users.user'),
        ),
        migrations.AlterField(
            model_name='subscriptionbox',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
