# Generated by Django 5.2.4 on 2025-07-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_scheduleditem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionbox',
            name='user',
        ),
    ]
