# Generated by Django 5.2.3 on 2025-06-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorproduct',
            old_name='product_ddetails_id',
            new_name='product_details_id',
        ),
    ]
