# Generated by Django 5.2.3 on 2025-06-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_ddetails_id_vendorproduct_product_details_id'),
        ('users', '0002_user_delete_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='users.user'),
        ),
    ]
