# Generated by Django 5.2.4 on 2025-07-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_buyer_alter_order_vendor'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='Unique Checkout Request ID from M-Pesa', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_request_id',
            field=models.CharField(default='12we', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa Transaction Receipt Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for payment', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_code',
            field=models.CharField(blank=True, help_text='M-Pesa Result Code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_desc',
            field=models.TextField(blank=True, help_text='M-Pesa Result Description', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of the transaction', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the payment record was last updated'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment record was created'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='M-Pesa', help_text='Payment method (M-Pesa)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['merchant_request_id'], name='payment_pay_merchan_5de281_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_request_id'], name='payment_pay_checkou_e2f706_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='payment_pay_order_i_211f02_idx'),
        ),
    ]
