# Generated by Django 5.2.4 on 2025-07-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_merchant_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='M-Pesa', help_text='Payment method', max_length=100),
        ),
    ]
