# Generated by Django 5.2.3 on 2025-06-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
