# Generated by Django 5.2.3 on 2025-06-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_vendorproduct_vendor'),
        ('users', '0002_user_delete_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
